{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uirouter-for-kcm/0.0.5/uirouter-for-kcm-0.0.5.module",
    "group": "io.github.istsest",
    "module": "uirouter-for-kcm",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "uirouter-for-kcm-iosX64Main-0.0.5.klib",
          "url": "uirouter-for-kcm-iosx64-0.0.5.klib",
          "size": 78715,
          "sha512": "4f6f00e3bd5c683038ff041ffddff4e994e7aaa470ed8273dd9aab5186bc61c53fb1bb59d711ad34882fc9f0e48e1e6fd083d5b1a04e20d720af4eb1c48a9ede",
          "sha256": "cfac3e613458fc55e023e541374052bb7c4386d026be23ef57013f2a1be03229",
          "sha1": "9a7461b3b749f065dde6293ba0ba6cdb5bb383c6",
          "md5": "94d7f746b4b773ed99730d0f6f646664"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "uirouter-for-kcm-iosx64-0.0.5-sources.jar",
          "url": "uirouter-for-kcm-iosx64-0.0.5-sources.jar",
          "size": 13559,
          "sha512": "ad0b4c67db108f7eee3054409eeb1dcb3560c75e22f93465e9e45932cd7ee284e8cad2a23a9438ff81439420b4f89f29bcf03669797d62a9d000659da9951375",
          "sha256": "af0be55a67e40dd74a0104f41bf704c96efc16db3f1d63c960835ca64426df28",
          "sha1": "cca2620e0b19d1e1dabdfdb0b1d5b855aea269ff",
          "md5": "ba3995275c23568d49f7afc46db9c77a"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "uirouter-for-kcm-0.0.5.kotlin_resources.zip",
          "url": "uirouter-for-kcm-iosx64-0.0.5-kotlin_resources.kotlin_resources.zip",
          "size": 356,
          "sha512": "0e44268c1f5dfc112c93f69784703f9491ab2b52f0237c7a5708d655a7dc4bf4c3bef937772d224e52749f2a2ad76185a306f58ced27a7ec76621bc84f4af0ab",
          "sha256": "c3ae0afdd00c48621dbd87b05d8b4344491f7e88e5370f86616d8a976cd54759",
          "sha1": "44aed169b0ddb82c693455fba9037ffde2ac1d86",
          "md5": "fd920a531f09658a1ce6c926c1bb388e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "uirouter-for-kcm-iosx64-0.0.5-metadata.jar",
          "url": "uirouter-for-kcm-iosx64-0.0.5-metadata.jar",
          "size": 261,
          "sha512": "ab6a79bb1ade5bad7e82ace4f93606698cee6b17f6daa1d2f312d3ac4e9ce6ea5959427548a514afbd8a0b70cea0693ba720842447f7774bdd9b7cf9602a6635",
          "sha256": "bed64af69bcd8e24d3862df8919582f31c4019853b93f6a6e1423c7946edc24d",
          "sha1": "7f74d19dfcb3aa5325105ca4df805973b9bb621c",
          "md5": "3b9f2903e73358d70775f845fb184293"
        }
      ]
    }
  ]
}
