{
  "formatVersion": "1.1",
  "component": {
    "url": "../../uirouter-for-kcm/0.0.5/uirouter-for-kcm-0.0.5.module",
    "group": "io.github.istsest",
    "module": "uirouter-for-kcm",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "uirouter-for-kcm-iosArm64Main-0.0.5.klib",
          "url": "uirouter-for-kcm-iosarm64-0.0.5.klib",
          "size": 78736,
          "sha512": "fdf8de7813082c5caa2f5d338ce19a50e6bf920c35ad5046facf0de7a54cd74f5ee78c036043d5fe65a39bd361adc7c7e95445a5ebca490a6805404ec3fde16e",
          "sha256": "ee4ea30c92ac09e2ee025ed5c253fdde19e6c9f23069230e02d83b484a70213c",
          "sha1": "06b5eaef6356340f1687de69c751f27f7af7e3f7",
          "md5": "ecb43f65d24490938084ce994a727d8e"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "uirouter-for-kcm-iosarm64-0.0.5-sources.jar",
          "url": "uirouter-for-kcm-iosarm64-0.0.5-sources.jar",
          "size": 13591,
          "sha512": "08e32a0dee326058d37f8eda9dc44ae4ac4567fb4a789188d6b03b358f2f82633d3e05cd856f1b4267768c775eac76a4b7bbc978fc7749d6ffb8db7b0e2513ef",
          "sha256": "e2f3b351ad1cc458be4c4de7df91ebcc434f5ffe6308b2acc4d0a836b7f8b53f",
          "sha1": "2942187e85cd915e54e75c7558af74735a2da270",
          "md5": "10e2631be913689e689984bb31e16da8"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "uirouter-for-kcm-0.0.5.kotlin_resources.zip",
          "url": "uirouter-for-kcm-iosarm64-0.0.5-kotlin_resources.kotlin_resources.zip",
          "size": 356,
          "sha512": "a91adcac8834424e10f5709d4697b172936728cdddaf9916d4dea527697b68103d4e4558cb42f7ae37e00308538bf22f717b06a8c91d1e916e04fa7451a3758b",
          "sha256": "cfc48b17dc966542ef61c5c954abb800e6ee59707ac0b897bd76b2f1c8e1aa5c",
          "sha1": "dfd609eab40e54270dcfa338a4b254146930a368",
          "md5": "06b0c127622bbb93923bd78ec4c98069"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "uirouter-for-kcm-iosarm64-0.0.5-metadata.jar",
          "url": "uirouter-for-kcm-iosarm64-0.0.5-metadata.jar",
          "size": 261,
          "sha512": "3cb6003a7c9b0d89758f3d6fca7775200e01b1314ab36413d4885c3d694b8c2d6926b9943eca933574f89532e012184fea15ff35ac4f8cc4c537cee716adc1f6",
          "sha256": "3c554c8cce58c24ff44764e7c515969a9326ecaa3b9b2136de3c980d67e2a200",
          "sha1": "77db5e8a9cd69d674ab050acb9ae73a20e9f959f",
          "md5": "b23deedd3021d84795df464b3a65ba76"
        }
      ]
    }
  ]
}
